name: PR Pipeline

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Lint only changed files
      run: |
          # Get list of changed JS files, excluding vendor directories
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.js$' | grep -v 'static/js/' | grep -v 'node_modules/' | xargs)
          if [ -n "$CHANGED_FILES" ]; then
            npx eslint $CHANGED_FILES
          else
            echo "No JavaScript files changed"
          fi
    
    - name: Run tests
      run: npm run test:ci
      env:
        SUPPRESS_LOGS: 'true'
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.node-version }}
        path: ./test-results/junit.xml
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        directory: ./coverage/
        token: ${{ secrets.CODECOV_TOKEN }}